// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: branches_service.proto

package orders_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BranchesServiceClient is the client API for BranchesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BranchesServiceClient interface {
	Create(ctx context.Context, in *CreateBranch, opts ...grpc.CallOption) (*Branch, error)
	GetById(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Branch, error)
	GetAll(ctx context.Context, in *BranchFilter, opts ...grpc.CallOption) (*Branches, error)
	Update(ctx context.Context, in *Branch, opts ...grpc.CallOption) (*Branch, error)
	Delete(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Void, error)
	CheckBranchExist(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Void, error)
	GetBranchTitleById(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*BranchTitle, error)
}

type branchesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBranchesServiceClient(cc grpc.ClientConnInterface) BranchesServiceClient {
	return &branchesServiceClient{cc}
}

func (c *branchesServiceClient) Create(ctx context.Context, in *CreateBranch, opts ...grpc.CallOption) (*Branch, error) {
	out := new(Branch)
	err := c.cc.Invoke(ctx, "/orders_service.branches_service/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) GetById(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Branch, error) {
	out := new(Branch)
	err := c.cc.Invoke(ctx, "/orders_service.branches_service/getById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) GetAll(ctx context.Context, in *BranchFilter, opts ...grpc.CallOption) (*Branches, error) {
	out := new(Branches)
	err := c.cc.Invoke(ctx, "/orders_service.branches_service/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) Update(ctx context.Context, in *Branch, opts ...grpc.CallOption) (*Branch, error) {
	out := new(Branch)
	err := c.cc.Invoke(ctx, "/orders_service.branches_service/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) Delete(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/orders_service.branches_service/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) CheckBranchExist(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/orders_service.branches_service/CheckBranchExist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *branchesServiceClient) GetBranchTitleById(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*BranchTitle, error) {
	out := new(BranchTitle)
	err := c.cc.Invoke(ctx, "/orders_service.branches_service/GetBranchTitleById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BranchesServiceServer is the server API for BranchesService service.
// All implementations must embed UnimplementedBranchesServiceServer
// for forward compatibility
type BranchesServiceServer interface {
	Create(context.Context, *CreateBranch) (*Branch, error)
	GetById(context.Context, *PrimaryKey) (*Branch, error)
	GetAll(context.Context, *BranchFilter) (*Branches, error)
	Update(context.Context, *Branch) (*Branch, error)
	Delete(context.Context, *PrimaryKey) (*Void, error)
	CheckBranchExist(context.Context, *PrimaryKey) (*Void, error)
	GetBranchTitleById(context.Context, *PrimaryKey) (*BranchTitle, error)
	mustEmbedUnimplementedBranchesServiceServer()
}

// UnimplementedBranchesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBranchesServiceServer struct {
}

func (UnimplementedBranchesServiceServer) Create(context.Context, *CreateBranch) (*Branch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBranchesServiceServer) GetById(context.Context, *PrimaryKey) (*Branch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedBranchesServiceServer) GetAll(context.Context, *BranchFilter) (*Branches, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedBranchesServiceServer) Update(context.Context, *Branch) (*Branch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBranchesServiceServer) Delete(context.Context, *PrimaryKey) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBranchesServiceServer) CheckBranchExist(context.Context, *PrimaryKey) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckBranchExist not implemented")
}
func (UnimplementedBranchesServiceServer) GetBranchTitleById(context.Context, *PrimaryKey) (*BranchTitle, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBranchTitleById not implemented")
}
func (UnimplementedBranchesServiceServer) mustEmbedUnimplementedBranchesServiceServer() {}

// UnsafeBranchesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BranchesServiceServer will
// result in compilation errors.
type UnsafeBranchesServiceServer interface {
	mustEmbedUnimplementedBranchesServiceServer()
}

func RegisterBranchesServiceServer(s grpc.ServiceRegistrar, srv BranchesServiceServer) {
	s.RegisterService(&BranchesService_ServiceDesc, srv)
}

func _BranchesService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders_service.branches_service/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).Create(ctx, req.(*CreateBranch))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders_service.branches_service/getById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).GetById(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BranchFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders_service.branches_service/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).GetAll(ctx, req.(*BranchFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Branch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders_service.branches_service/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).Update(ctx, req.(*Branch))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders_service.branches_service/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).Delete(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_CheckBranchExist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).CheckBranchExist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders_service.branches_service/CheckBranchExist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).CheckBranchExist(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _BranchesService_GetBranchTitleById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BranchesServiceServer).GetBranchTitleById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders_service.branches_service/GetBranchTitleById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BranchesServiceServer).GetBranchTitleById(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// BranchesService_ServiceDesc is the grpc.ServiceDesc for BranchesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BranchesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "orders_service.branches_service",
	HandlerType: (*BranchesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _BranchesService_Create_Handler,
		},
		{
			MethodName: "getById",
			Handler:    _BranchesService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _BranchesService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _BranchesService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BranchesService_Delete_Handler,
		},
		{
			MethodName: "CheckBranchExist",
			Handler:    _BranchesService_CheckBranchExist_Handler,
		},
		{
			MethodName: "GetBranchTitleById",
			Handler:    _BranchesService_GetBranchTitleById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "branches_service.proto",
}
