// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: user_locations.proto

package users

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserLocationServiceClient is the client API for UserLocationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserLocationServiceClient interface {
	Create(ctx context.Context, in *CreateUserLocation, opts ...grpc.CallOption) (*UserLocation, error)
	GetById(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*UserLocation, error)
	GetAll(ctx context.Context, in *UserLocationFilter, opts ...grpc.CallOption) (*UserLocations, error)
	Update(ctx context.Context, in *UpdateUserLocation, opts ...grpc.CallOption) (*UserLocation, error)
	Delete(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Void, error)
}

type userLocationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserLocationServiceClient(cc grpc.ClientConnInterface) UserLocationServiceClient {
	return &userLocationServiceClient{cc}
}

func (c *userLocationServiceClient) Create(ctx context.Context, in *CreateUserLocation, opts ...grpc.CallOption) (*UserLocation, error) {
	out := new(UserLocation)
	err := c.cc.Invoke(ctx, "/users.UserLocationService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLocationServiceClient) GetById(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*UserLocation, error) {
	out := new(UserLocation)
	err := c.cc.Invoke(ctx, "/users.UserLocationService/GetById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLocationServiceClient) GetAll(ctx context.Context, in *UserLocationFilter, opts ...grpc.CallOption) (*UserLocations, error) {
	out := new(UserLocations)
	err := c.cc.Invoke(ctx, "/users.UserLocationService/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLocationServiceClient) Update(ctx context.Context, in *UpdateUserLocation, opts ...grpc.CallOption) (*UserLocation, error) {
	out := new(UserLocation)
	err := c.cc.Invoke(ctx, "/users.UserLocationService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userLocationServiceClient) Delete(ctx context.Context, in *PrimaryKey, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/users.UserLocationService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserLocationServiceServer is the server API for UserLocationService service.
// All implementations must embed UnimplementedUserLocationServiceServer
// for forward compatibility
type UserLocationServiceServer interface {
	Create(context.Context, *CreateUserLocation) (*UserLocation, error)
	GetById(context.Context, *PrimaryKey) (*UserLocation, error)
	GetAll(context.Context, *UserLocationFilter) (*UserLocations, error)
	Update(context.Context, *UpdateUserLocation) (*UserLocation, error)
	Delete(context.Context, *PrimaryKey) (*Void, error)
	mustEmbedUnimplementedUserLocationServiceServer()
}

// UnimplementedUserLocationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserLocationServiceServer struct {
}

func (UnimplementedUserLocationServiceServer) Create(context.Context, *CreateUserLocation) (*UserLocation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserLocationServiceServer) GetById(context.Context, *PrimaryKey) (*UserLocation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedUserLocationServiceServer) GetAll(context.Context, *UserLocationFilter) (*UserLocations, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedUserLocationServiceServer) Update(context.Context, *UpdateUserLocation) (*UserLocation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserLocationServiceServer) Delete(context.Context, *PrimaryKey) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserLocationServiceServer) mustEmbedUnimplementedUserLocationServiceServer() {}

// UnsafeUserLocationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserLocationServiceServer will
// result in compilation errors.
type UnsafeUserLocationServiceServer interface {
	mustEmbedUnimplementedUserLocationServiceServer()
}

func RegisterUserLocationServiceServer(s grpc.ServiceRegistrar, srv UserLocationServiceServer) {
	s.RegisterService(&UserLocationService_ServiceDesc, srv)
}

func _UserLocationService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserLocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLocationServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserLocationService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLocationServiceServer).Create(ctx, req.(*CreateUserLocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLocationService_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLocationServiceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserLocationService/GetById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLocationServiceServer).GetById(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLocationService_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserLocationFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLocationServiceServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserLocationService/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLocationServiceServer).GetAll(ctx, req.(*UserLocationFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLocationService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserLocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLocationServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserLocationService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLocationServiceServer).Update(ctx, req.(*UpdateUserLocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserLocationService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserLocationServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/users.UserLocationService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserLocationServiceServer).Delete(ctx, req.(*PrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// UserLocationService_ServiceDesc is the grpc.ServiceDesc for UserLocationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserLocationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "users.UserLocationService",
	HandlerType: (*UserLocationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserLocationService_Create_Handler,
		},
		{
			MethodName: "GetById",
			Handler:    _UserLocationService_GetById_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _UserLocationService_GetAll_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserLocationService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserLocationService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_locations.proto",
}
